import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Rajdhani } from "next/font/google";
import { ClanProvider } from "@/context/ClanContext";

const rajdhani = Rajdhani({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Choose the font weights you need
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clans",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`{rajdhani.variable} antialiased`}>
        <div className="container max-w-[1920px] overflow-x-hidden mx-auto">
          <ClanProvider>{children}</ClanProvider>
        </div>
      </body>
    </html>
  );
}
