name: Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# jobs:

#   build:

#     runs-on: ubuntu-latest
#     steps: 
#     - name: Login to Amazon ECR
#       id: login-ecr
#       uses: aws-actions/amazon-ecr-login@v2
#       with:
#         mask-password: 'true'
#     steps:
#     - uses: actions/checkout@v4
#     - name: Build the Docker image
#       run: docker build -t clans-landing-page:latest .



jobs:
  deploy:
    name: Build image and push to Amazon ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'true'
    - name: Build image
      run: |
        docker build -t clans-landing-page:latest .

    - name: Tag, and push image to Amazon ECR
      env:
        # ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        
        ECR_REPOSITORY: "kaifoundry/clans-landing-page"        
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker tag clans-landing-page $ECR_REGISTRY/$ECR_REPOSITORY
        docker tag clans-landing-page $ECR_REGISTRY/$ECR_REPOSITORY
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.event.inputs.tag }}
